/// Event constants for MusicKit plugin
pub const PLAYER_ADAPTER_EVENTS_INITIALIZED: &str = "PLAYER_ADAPTER_EVENTS.INITIALIZED";
pub const PLAYER_ADAPTER_EVENTS_AUTHORIZATION_STATUS_CHANGE: &str = "PLAYER_ADAPTER_EVENTS.AUTHORIZATION_STATUS_CHANGE";
pub const PLAYER_ADAPTER_EVENTS_STATE_UPDATE: &str = "PLAYER_ADAPTER_EVENTS.STATE_UPDATE";
pub const PLAYER_ADAPTER_EVENTS_QUEUE_UPDATE: &str = "PLAYER_ADAPTER_EVENTS.QUEUE_UPDATE";
pub const PLAYER_ADAPTER_EVENTS_TRACK_CHANGE: &str = "PLAYER_ADAPTER_EVENTS.TRACK_CHANGE";
pub const PLAYER_ADAPTER_EVENTS_ERROR: &str = "PLAYER_ADAPTER_EVENTS.ERROR"; 